/// Daily Rashifal data, as published for one calendar date.
///
/// A day's reading is a date key plus every sign's content, in one or more
/// languages. Everything here is generated by `scripts/generate_rashifal.py`
/// and stored under `data/rashifal/YYYY-MM-DD.json`; nothing in this library
/// invents a reading.
///
/// The content is original daily guidance based on traditional astrological
/// beliefs. It is not a scientific prediction, and the UI must always say so.
library;

import 'dart:convert';

/// The twelve signs, in the traditional order.
///
/// These are the stable keys used both in storage and inside the generated JSON,
/// so the data model never has to translate between a file's sign key and the
/// display order.
const List<String> kRashifalSignKeys = <String>[
  'mesha',
  'vrishabha',
  'mithun',
  'karka',
  'simha',
  'kanya',
  'tula',
  'vrishchik',
  'dhanu',
  'makar',
  'kumbh',
  'meen',
];

/// Languages this data can carry, keyed the way Flutter keys them.
const List<String> kRashifalLanguages = <String>['hi', 'en'];

/// One sign's reading for one day.
///
/// All eight categories are required: a generated day either carries the full
/// set or it is not a usable day.
class SignRashifal {
  const SignRashifal({
    required this.signKey,
    required this.general,
    required this.career,
    required this.finance,
    required this.love,
    required this.health,
    required this.luckyNumber,
    required this.luckyColour,
    required this.guidance,
  });

  final String signKey;
  final String general;
  final String career;
  final String finance;
  final String love;
  final String health;
  final int luckyNumber;
  final String luckyColour;
  final String guidance;

  Map<String, Object?> toJson() => <String, Object?>{
        'general': general,
        'career': career,
        'finance': finance,
        'love': love,
        'health': health,
        'luckyNumber': luckyNumber,
        'luckyColour': luckyColour,
        'guidance': guidance,
      };

  static SignRashifal? _tryParse(String signKey, Object? raw) {
    if (raw is! Map) return null;
    final m = raw.cast<Object?, Object?>();
    String? str(String key) {
      final v = m[key];
      if (v is! String) return null;
      final t = v.trim();
      return t.isEmpty ? null : t;
    }

    final general = str('general');
    final career = str('career');
    final finance = str('finance');
    final love = str('love');
    final health = str('health');
    final colour = str('luckyColour');
    final guidance = str('guidance');

    final num = m['luckyNumber'];
    final luckyNumber =
        num is int ? num : (num is String ? int.tryParse(num.trim()) : null);

    // Every category must be present and non-empty, and the lucky number must be
    // a sensible positive integer.
    if (general == null ||
        career == null ||
        finance == null ||
        love == null ||
        health == null ||
        colour == null ||
        guidance == null ||
        luckyNumber == null ||
        luckyNumber < 1 ||
        luckyNumber > 9) {
      return null;
    }

    return SignRashifal(
      signKey: signKey,
      general: general,
      career: career,
      finance: finance,
      love: love,
      health: health,
      luckyNumber: luckyNumber,
      luckyColour: colour,
      guidance: guidance,
    );
  }
}

/// One complete day of readings, in one or more languages.
class DailyRashifal {
  const DailyRashifal({
    required this.date,
    required this.languages,
  });

  /// The calendar date this data belongs to, as `YYYY-MM-DD`.
  ///
  /// Comparing this against the date the user is looking at is what stops a stale
  /// day from being presented as today's reading.
  final String date;

  /// Content per language, each covering all twelve signs.
  final Map<String, Map<String, SignRashifal>> languages;

  /// Signs present for [language].
  Map<String, SignRashifal> signsFor(String language) =>
      languages[language] ?? const <String, SignRashifal>{};

  /// Whether [language] has a reading for [signKey].
  bool has(String language, String signKey) =>
      signsFor(language).containsKey(signKey);

  /// True when every known language covers all twelve signs in full.
  bool get isComplete => kRashifalLanguages.every(_isLanguageComplete);

  /// Whether [language] covers all twelve signs with all eight categories.
  bool _isLanguageComplete(String language) {
    final signs = signsFor(language);
    return kRashifalSignKeys.every(signs.containsKey);
  }

  /// Signs missing for [language], in canonical order.
  List<String> missingSignsFor(String language) => kRashifalSignKeys
      .where((k) => !signsFor(language).containsKey(k))
      .toList();

  /// True when this day carries no content for [language] at all.
  bool isEmptyFor(String language) => signsFor(language).isEmpty;

  /// Parses generated JSON.
  ///
  /// Returns `null` when the payload is not a usable day rather than throwing, so
  /// callers can treat a corrupt or partial file as "unavailable" and fall back
  /// instead of crashing.
  static DailyRashifal? tryParse(String source) {
    try {
      final decoded = jsonDecode(source);
      if (decoded is! Map) return null;
      final root = decoded.cast<Object?, Object?>();

      final date = root['date'];
      if (date is! String || !_isValidDateKey(date)) return null;

      final languagesRaw = root['languages'];
      if (languagesRaw is! Map) return null;

      final languages = <String, Map<String, SignRashifal>>{};
      for (final entry in languagesRaw.entries) {
        if (entry.key is! String) continue;
        final lang = entry.key as String;
        if (!kRashifalLanguages.contains(lang)) continue;
        if (entry.value is! Map) continue;
        final signsRaw = entry.value.cast<Object?, Object?>();
        final signs = <String, SignRashifal>{};
        for (final key in kRashifalSignKeys) {
          final parsed = SignRashifal._tryParse(key, signsRaw[key]);
          if (parsed == null) continue;
          signs[key] = parsed;
        }
        // A language with nothing in it is not worth keeping.
        if (signs.isEmpty) continue;
        languages[lang] = signs;
      }

      if (languages.isEmpty) return null;
      return DailyRashifal(date: date, languages: languages);
    } catch (_) {
      return null;
    }
  }

  /// Serialises back to the generated shape, used when writing the cache.
  Map<String, Object?> toJson() => <String, Object?>{
        'date': date,
        'languages': <String, Object?>{
          for (final entry in languages.entries)
            entry.key: <String, Object?>{
              for (final s in entry.value.entries) s.key: s.value.toJson(),
            },
        },
      };
}

/// Validates a `YYYY-MM-DD` date key, rejecting anything else.
///
/// The day-level granularity is the whole point of the system: a key that names
/// a time, or a differently shaped string, cannot be matched against a calendar
/// day safely.
bool isValidDateKey(String value) => _isValidDateKey(value);

bool _isValidDateKey(String value) {
  final match = RegExp(r'^(\d{4})-(\d{2})-(\d{2})$').firstMatch(value);
  if (match == null) return false;
  final year = int.parse(match.group(1)!);
  final month = int.parse(match.group(2)!);
  final day = int.parse(match.group(3)!);
  if (month < 1 || month > 12) return false;
  if (day < 1 || day > daysInMonth(year, month)) return false;
  return true;
}

/// Days in [month] of [year], leap years included.
int daysInMonth(int year, int month) {
  const lengths = <int>[31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];
  if (month == 2 && isLeapYear(year)) return 29;
  return lengths[month - 1];
}

bool isLeapYear(int year) =>
    (year % 4 == 0 && year % 100 != 0) || year % 400 == 0;

/// Formats a [DateTime] as the `YYYY-MM-DD` key used everywhere.
String dateKeyOf(DateTime d) => '${d.year.toString().padLeft(4, '0')}-'
    '${d.month.toString().padLeft(2, '0')}-'
    '${d.day.toString().padLeft(2, '0')}';

DateTime dateFromKey(String key) {
  final parts = key.split('-');
  return DateTime(
    int.parse(parts[0]),
    int.parse(parts[1]),
    int.parse(parts[2]),
  );
}

/// Splits a `YYYY-MM-DD` key into its parts, or `null` when malformed.
List<int>? datePartsOf(String key) {
  final parts = key.split('-');
  if (parts.length != 3) return null;
  final year = int.tryParse(parts[0]);
  final month = int.tryParse(parts[1]);
  final day = int.tryParse(parts[2]);
  if (year == null || month == null || day == null) return null;
  return <int>[year, month, day];
}
