import 'package:flutter/widgets.dart';

class AppLocalizations {
  AppLocalizations(this.locale);
  final Locale locale;
  static const delegate = _Delegate();
  static AppLocalizations of(BuildContext c) =>
      Localizations.of<AppLocalizations>(c, AppLocalizations)!;

  static const Map<String, Map<String, String>> _v = {
    'hi': {
      'app': 'JapMitra',
      'tag': 'आपका दैनिक आध्यात्मिक साथी',
      'made': 'Vinayakam Solutions द्वारा निर्मित',
      'next': 'आगे',
      'skip': 'छोड़ें',
      'getStarted': 'शुरू करें',
      'city': 'आपका शहर',
      'home': 'Home',
      'jap': 'Jap',
      'panchang': 'Panchang',
      'rashifal': 'Rashifal',
      'more': 'More',
      'todayJap': 'आज का Jap',
      'doJap': 'Jap करें',
      'fullPanchang': 'पूरा पंचांग',
      'fullRashifal': 'पूरा राशिफल',
      'numerology': 'Numerology',
      'settings': 'सेटिंग्स',
      'language': 'भाषा',
      'goal': 'दैनिक लक्ष्य',
      'reset': 'रीसेट',
      'confirmReset': 'आज का Jap रीसेट करें?',
      'resetExplain':
          'सिर्फ आज के इस मंत्र के Jap हटेंगे। पिछले दिनों का इतिहास सुरक्षित रहेगा।',
      'cancel': 'रद्द करें',
      'ok': 'ठीक है',
      'confirm': 'पुष्टि करें',
      'sample':
          'यह डेवलपमेंट/नमूना डेटा है — रिलीज़ से पहले verified डेटा जोड़ें.',
      'unavailable': 'अभी उपलब्ध नहीं है',
      'reminder': 'दैनिक Jap अनुस्मारक',
      'reminderTime': 'अनुस्मारक का समय',
      'enable': 'चालू करें',
      'disable': 'बंद करें',
      'selectMantra': 'मंत्र चुनें',
      'customMantra': 'अपना मंत्र',
      'emptyMantra': 'मंत्र खाली नहीं हो सकता',
      'birthNumber': 'जन्म अंक',
      'notSci': 'सांस्कृतिक/मनोरंजन के लिए — यह वैज्ञानिक निश्चितता नहीं है।',
      'lifePath': 'भाग्य अंक (Life Path)',
      'todayNumber': 'आज का अंक',
      'luckyNumber': 'लकी नंबर',
      'luckyColour': 'लकी रंग',
      'dailyGuidance': 'दैनिक मार्गदर्शन',
      'general': 'सामान्य',
      'career': 'करियर',
      'finance': 'वित्त',
      'relationships': 'प्रेम/संबंध',
      'health': 'स्वास्थ्य/कल्याण',
      'guidanceOnly':
          'यह केवल भक्ति/मनोरंजन मार्गदर्शन है, वैज्ञानिक भविष्यवाणी नहीं।',
      'todayCount': 'आज की जाप',
      'lifetime': 'जीवनकाल Jap',
      'sessionCount': 'इस सत्र के Jap',
      'mala': 'माला',
      'malaComplete': 'माला पूर्ण',
      'malaMessage':
          'आपकी जाप माला पूर्ण हुई। प्रभु का आशीर्वाद आप पर बना रहे।',
      'malaMessageDeity': 'आपकी जाप माला पूर्ण हुई।',
      'endSessionTitle': 'Jap सत्र समाप्त करें?',
      'endSessionBody': 'अब तक की आपकी प्रगति सुरक्षित रूप से सहेज ली गई है।',
      'endSession': 'सत्र समाप्त',
      'resetSecondary': 'रीसेट',
      'currentStreak': 'चालू स्ट्रीक',
      'bestStreak': 'सर्वोत्तम स्ट्रीक',
      'streak': 'स्ट्रीक',
      'history': 'दैनिक इतिहास',
      'historyExplain': 'पिछले दिनों के इस मंत्र के जाप',
      'noHistory': 'अभी कोई इतिहास उपलब्ध नहीं है',
      'tapToJap': 'जाप करने के लिए दबाएँ',
      'tapAccessibility': 'जाप गिनने के लिए दबाएँ',
      'session': 'सत्र',
      'tapHint': 'कहीं भी टैप करें',
      'progress': 'प्रगति',
      'goalReached': 'आज का लक्ष्य पूर्ण!',
      'om': 'ॐ',
      'sunrise': 'सूर्योदय',
      'sunset': 'सूर्यास्त',
      'moonrise': 'चंद्रोदय',
      'moonset': 'चंद्रास्त',
      'tithi': 'तिथि',
      'paksha': 'पक्ष',
      'nakshatra': 'नक्षत्र',
      'nakshatraPada': 'नक्षत्र/चरण',
      'yoga': 'योग',
      'karana': 'करण',
      'rahuKaal': 'राहु काल',
      'yamaganda': 'यमगंड',
      'gulika': 'गुलिका',
      'abhijitMuhurat': 'अभिजीत मुहूर्त',
      'sankranti': 'संक्रांति',
      'vrat': 'व्रत',
      'festivals': 'त्योहार',
      'ekadashi': 'एकादशी',
      'purnima': 'पूर्णिमा',
      'amavasya': 'अमावस्या',
      'ashtami': 'अष्टमी',
      'pradosh': 'प्रदोष',
      'prevDay': 'पिछला दिन',
      'nextDay': 'अगला दिन',
      'monthNav': 'माह चुनें',
      'selectDate': 'तिथि चुनें',
      'dailyPanchang': 'दैनिक पंचांग',
      'coordinates': 'निर्देशांक',
      'timezoneNote': 'समय क्षेत्र: +05:30 (IST)',
      'astronomicalApprox':
          'खगोलीय गणना सन्निकट है; कुछ मिनटों का अंतर संभव है। महत्वपूर्ण कार्यों हेतु विशेषज्ञ से पुष्टि करें।',
      'panchangDisclaimer':
          'पंचांग की गणना मानक खगोलीय विधियों से की जाती है और सन्निकट हो सकती है।',
      'rashi': 'राशि',
      'mysign': 'मेरी राशि',
      'bell': 'घंटी',
      'softBell': 'मृदु घंटी',
      'vibration': 'कंपन',
      'vibrationHint': 'जाप पर हल्का कंपन',
      'vibrationOff': 'बंद',
      'vibrationEvery': 'हर जाप पर',
      'vibrationEvery10': 'हर 10 जाप पर',
      'vibrationMala': 'माला पूर्ण पर',
      'sound': 'ध्वनि',
      'soundOff': 'बंद',
      'soundHint': 'अनुस्मारक की ध्वनि',
      'reminderVibration': 'अनुस्मारक कंपन',
      'reminderSound': 'अनुस्मारक ध्वनि',
      'theme': 'थीम',
      'themeLight': 'उजला',
      'themeDark': 'गहरा',
      'themeSystem': 'सिस्टम जैसा',
      'about': 'JapMitra के बारे में',
      'aboutDesc':
          'JapMitra आपका दैनिक आध्यात्मिक साथी है। यह ऐप आपको नाम जप ट्रैक करने, पंचांग देखने, राशिफल और अंक ज्यामिति का उपयोग करने में मदद करता है। सभी डेटा आपके डिवाइस पर स्थानीय रूप से संग्रहीत होता है।',
      'privacy': 'गोपनीयता नीति',
      'privacyBody':
          'JapMitra सभी डेटा (जाप गिनती, लक्ष्य, सेटिंग्स, अनुस्मारक) आपके डिवाइस पर ही स्थानीय रूप से संग्रहीत करता है। कोई व्यक्तिगत जानकारी सर्वर पर नहीं भेजी जाती। जाप, नाम और शहर की जानकारी केवल आपके इन-ऐप अनुभव के लिए उपयोग होती है। ऐप द्वारा कभी भी डेटा बेचा या साझा नहीं किया जाता।',
      'privacyOk': 'समझ गया',
      'terms': 'नियम एवं शर्तें',
      'termsBody':
          'JapMitra का उपयोग करके आप सहमत होते हैं कि:\n\n1. यह ऐप केवल व्यक्तिगत आध्यात्मिक उपयोग के लिए है।\n2. अंक ज्यामिति और राशिफल केवल सांस्कृतिक/मनोरंजन उद्देश्यों के लिए हैं और वैज्ञानिक भविष्यवाणी नहीं हैं।\n3. सभी डेटा स्थानीय रूप से संग्रहीत होता है; कोई डेटा सर्वर पर नहीं भेजा जाता।\n4. पंचांग गणना मानक खगोलीय विधियों पर आधारित है और सन्निकट हो सकती है।',
      'contactFeedback': 'संपर्क/प्रतिक्रिया',
      'contactFeedbackBody':
          'आपकी प्रतिक्रिया हमारे लिए महत्वपूर्ण है!\n\nईमेल करें: support@vinayakamsolutions.com\n\nऐप के बारे में सुझाव, समस्याएँ या प्रश्न साझा करें।',
      'gallery': 'भक्ति दर्शन',
      'gallerySubtitle': 'देव-दर्शन संग्रह',
      'artworkSoon': 'चित्र शीघ्र उपलब्ध होगा',
      'artworkSoonBody':
          'इस संग्रह की कलाकृति अभी उपलब्ध नहीं है। वर्णन नीचे दिया गया है।',
      'collection': 'संग्रह',
      'item': 'वस्तु',
      'detail': 'विवरण',
      'adFreeNote': 'यह स्क्रीन अनुभव के मध्य में कभी विज्ञापन नहीं दिखाती।',
      'bannerAds': 'विज्ञापन',
      'premium': 'प्रीमियम',
      'adSupportNote': 'जाप के दौरान कभी विज्ञापन नहीं दिखाया जाता।',
      'notifications': 'सूचनाएँ',
      'notificationPermission': 'अनुस्मारक के लिए सूचना अनुमति आवश्यक है।',
      'permissionDenied':
          'सूचना अनुमति नहीं मिली। आप इसे सिस्टम सेटिंग्स से चालू कर सकते हैं।',
      'notifTitle': 'JapMitra',
      'notifBody': 'आपका दैनिक Jap समय आ गया।',
      'notifBodyMantra': 'अपना दैनिक Jap पूर्ण करें।',
      'setDob': 'जन्म तिथि चुनें',
      'editDob': 'जन्म तिथि बदलें: ',
      'deleteDob': 'जन्म तिथि हटाएँ',
      'dobPrefix': 'DOB: ',
      'announcement': 'विशेष',
      'inspiration': 'प्रेरणा',
      'quoteDaily': 'हर दिन नया संकल्प, नया विश्वास।',
      'from': 'से',
      'goalSetting': 'दैनिक लक्ष्य',
      'malaShort': 'Mala',
      'today': 'आज',
      'yesterday': 'कल',
      'days': 'दिन',
      'sanskritWrong': 'गहराई से: मंत्र सटीकता की समीक्षा जारी है।',
      'builtIn': 'बिल्ट-इन',
      'japNow': 'Jap शुरू करें',
      'resume': 'जारी रखें',
      'selected': 'चुना हुआ',
      'close': 'बंद करें',
      'deities': 'देवता',
      'temples': 'मंदिर',
      'festivalToday': 'आज का त्योहार',
      'rashifalDesc': 'आज का राशिफल देखें',
      'astroTitle': 'आचार्य से परामर्श',
      'astroSubtitle': 'निजी कॉल पर व्यक्तिगत मार्गदर्शन',
      'astroSpecialities': 'विशेषताएँ',
      'astroLanguages': 'भाषाएँ',
      'astroAvailability': 'उपलब्ध',
      'astroBasedIn': 'आधारित',
      'astroFee': 'परामर्श शुल्क',
      'astroMinutes': 'मिनट',
      'astroCall': 'कॉल करें',
      'astroWhatsapp': 'व्हाट्सएप',
      'astroCallFailed':
          'कॉल शुरू नहीं हो सकी। कृपया नंबर मैन्युअली डायल करें।',
      'astroWhatsappFailed':
          'व्हाट्सएप नहीं खुल सका। कृपया नंबर मैन्युअली डायल करें।',
      'astroNoBooking':
          'ऐप में भुगतान या बुकिंग नहीं होती — कृपया सीधे कॉल करें।',
      'mantraFontSize': 'मंत्र का फ़ॉन्ट आकार',
      'mantraFontSizeNote':
          'यह केवल मंत्र का दिखने वाला आकार बदलता है — आपके जाप की गिनती पर कोई असर नहीं होता।',
      'sizeSmall': 'छोटा',
      'sizeMedium': 'मध्यम',
      'sizeLarge': 'बड़ा',
      'sizeExtraLarge': 'बहुत बड़ा',
      'myRashi': 'मेरी राशि',
      'setAsMySign': 'मेरी राशि बनाएँ',
      'clearMySign': 'मेरी राशि हटाएँ',
      'rashiNotSetNote': 'अपनी राशि चुनें, वह यहाँ हाइलाइट हो जाएगी।',
      'rashifalUnavailableNote':
          'आज की राशिफल सामग्री अभी उपलब्ध नहीं है। हम केवल सत्यापित स्रोत से ही राशिफल दिखाते हैं।',
      'rashifalToday': 'आज का राशिफल',
      'rashifalPrevDay': 'पिछला दिन',
      'rashifalNextDay': 'अगला दिन',
      'rashifalTodayShort': 'आज',
      'rashifalPickSign': 'राशि चुनें',
      'rashifalFutureNote':
          'भविष्य की तारीख का राशिफल उपलब्ध नहीं है। कृपया आज या कोई पिछली तारीख चुनें।',
      'rashifalFromCache': 'ऑफ़लाइन — सहेजा गया डेटा',
      'rashifalFromRemote': 'ताज़ा डेटा',
      'rashifalRetry': 'पुनः प्रयास',
      'rashifalDisclaimer':
          'यह राशिफल पारंपरिक ज्योतिषीय मान्यताओं पर आधारित दैनिक मार्गदर्शन है। इसे वैज्ञानिक भविष्यवाणी या निश्चित परिणाम के रूप में न लें।',
      'calculate': 'गणना करें',
      'calculateNumerology': 'मेरी संख्याएँ गणना करें',
      'forDate': 'तारीख़',
      'traditionalNote':
          'नामुम्र के पारंपरिक संबंध — वैज्ञानिक भविष्यवाणी नहीं।',
      'astroPhotoLabel': 'ज्योतिषाचार्य का चित्र',
      'customMantraName': 'मंत्र का नाम',
      'optional': 'वैकल्पिक',
      'customMantraText': 'मंत्र का पाठ',
      'deityPhoto': 'देवी/देवता की फोटो',
      'choosePhoto': 'फोटो चुनें',
      'replacePhoto': 'फोटो बदलें',
      'removePhoto': 'फोटो हटाएँ',
      'addCustomMantra': 'नया मंत्र जोड़ें',
      'deleteCustomMantra': 'मंत्र हटाएँ',
      'deleteCustomMantraBody':
          'यह मंत्र और उसकी जप गिनती हमेशा के लिए हट जाएगी।',
      'customMantraAdded': 'मंत्र जोड़ दिया गया।',
      'photoFailed': 'फोटो नहीं जोड़ी जा सकी — मंत्र फोटो के बिना सहेजा गया।',
      'noFestivalToday': 'आज कोई त्योहार या व्रत नहीं है।',
      'viewFullPanchang': 'पूरा पंचांग देखें',
      'timings': 'समय',
    },
    'en': {
      'app': 'JapMitra',
      'tag': 'Your Daily Spiritual Companion',
      'made': 'Made by Vinayakam Solutions',
      'next': 'Next',
      'skip': 'Skip',
      'getStarted': 'Get Started',
      'city': 'Your city',
      'home': 'Home',
      'jap': 'Jap',
      'panchang': 'Panchang',
      'rashifal': 'Rashifal',
      'more': 'More',
      'todayJap': "Today's Jap",
      'doJap': 'Start Jap',
      'fullPanchang': 'Full Panchang',
      'fullRashifal': 'Full Rashifal',
      'numerology': 'Numerology',
      'settings': 'Settings',
      'language': 'Language',
      'goal': 'Daily Goal',
      'reset': 'Reset',
      'confirmReset': "Reset today's Jap?",
      'resetExplain':
          "Only today's Jap for this mantra will be removed. Previous days remain untouched.",
      'cancel': 'Cancel',
      'ok': 'OK',
      'confirm': 'Confirm',
      'sample':
          'Development/sample data only — add verified data before production release.',
      'unavailable': 'Not available yet',
      'reminder': 'Daily Jap reminder',
      'reminderTime': 'Reminder time',
      'enable': 'Enable',
      'disable': 'Disable',
      'selectMantra': 'Select Mantra',
      'customMantra': 'Custom Mantra',
      'emptyMantra': 'Mantra cannot be empty',
      'birthNumber': 'Birth Number',
      'notSci':
          'For cultural/entertainment purposes. Not scientific certainty.',
      'lifePath': 'Life Path Number',
      'todayNumber': "Today's Number",
      'luckyNumber': 'Lucky Number',
      'luckyColour': 'Lucky Colour',
      'dailyGuidance': 'Daily Guidance',
      'general': 'General',
      'career': 'Career',
      'finance': 'Finance',
      'relationships': 'Love/Relationships',
      'health': 'Health/Wellbeing',
      'guidanceOnly':
          'This is devotional/entertainment guidance only, not a scientific prediction.',
      'todayCount': "Today's Jap",
      'lifetime': 'Lifetime Jap',
      'sessionCount': 'Session Jap',
      'mala': 'Mala',
      'malaComplete': 'Mala Complete',
      'malaMessage':
          'Your Jap mala is complete. May divine blessings remain with you.',
      'malaMessageDeity': 'Your Jap mala is complete.',
      'endSessionTitle': 'End Jap Session?',
      'endSessionBody': 'Your progress so far has been saved safely.',
      'endSession': 'End Session',
      'resetSecondary': 'Reset',
      'currentStreak': 'Current Streak',
      'bestStreak': 'Best Streak',
      'streak': 'Streak',
      'history': 'Daily History',
      'historyExplain': 'Jap counts for this mantra on past days',
      'noHistory': 'No history available yet',
      'tapToJap': 'Tap to do Jap',
      'tapAccessibility': 'Tap to count Jap',
      'session': 'Session',
      'tapHint': 'Tap anywhere to count',
      'progress': 'Progress',
      'goalReached': "Today's goal reached!",
      'om': 'Om',
      'sunrise': 'Sunrise',
      'sunset': 'Sunset',
      'moonrise': 'Moonrise',
      'moonset': 'Moonset',
      'tithi': 'Tithi',
      'paksha': 'Paksha',
      'nakshatra': 'Nakshatra',
      'nakshatraPada': 'Nakshatra/Pada',
      'yoga': 'Yoga',
      'karana': 'Karana',
      'rahuKaal': 'Rahu Kaal',
      'yamaganda': 'Yamaganda',
      'gulika': 'Gulika',
      'abhijitMuhurat': 'Abhijit Muhurat',
      'sankranti': 'Sankranti',
      'vrat': 'Vrat',
      'festivals': 'Festivals',
      'ekadashi': 'Ekadashi',
      'purnima': 'Purnima',
      'amavasya': 'Amavasya',
      'ashtami': 'Ashtami',
      'pradosh': 'Pradosha',
      'prevDay': 'Previous day',
      'nextDay': 'Next day',
      'monthNav': 'Choose month',
      'selectDate': 'Choose date',
      'dailyPanchang': 'Daily Panchang',
      'coordinates': 'Coordinates',
      'timezoneNote': 'Timezone: +05:30 (IST)',
      'astronomicalApprox':
          'Astronomical calculation is approximate; small variance is possible. Please confirm with an expert for critical events.',
      'panchangDisclaimer':
          'Panchang values are computed from standard astronomical methods and may be approximate.',
      'rashi': 'Rashi',
      'mysign': 'My rashi',
      'bell': 'Bell',
      'softBell': 'Soft Bell',
      'vibration': 'Vibration',
      'vibrationHint': 'Gentle vibration on Jap tap',
      'vibrationOff': 'Off',
      'vibrationEvery': 'Every Jap',
      'vibrationEvery10': 'Every 10 Jap',
      'vibrationMala': 'On Mala Complete',
      'sound': 'Sound',
      'soundOff': 'Off',
      'soundHint': 'Reminder sound',
      'reminderVibration': 'Reminder vibration',
      'reminderSound': 'Reminder sound',
      'theme': 'Theme',
      'themeLight': 'Light',
      'themeDark': 'Dark',
      'themeSystem': 'System',
      'about': 'About JapMitra',
      'aboutDesc':
          'JapMitra is your daily spiritual companion. Track your Jap, view Panchang, Rashifal, and Numerology — all stored locally on your device.',
      'privacy': 'Privacy Policy',
      'privacyBody':
          'JapMitra stores all data (Jap counts, goals, settings, reminders) locally on your device. No personal information is sent to any server. Jap, name and city details are used only for your in-app experience. The app never sells or shares your data.',
      'privacyOk': 'Got it',
      'terms': 'Terms of Use',
      'termsBody':
          'By using JapMitra, you agree that:\n\n1. This app is for personal spiritual use only.\n2. Numerology and Rashifal are for cultural/entertainment purposes and are not scientific predictions.\n3. All data is stored locally; no data is sent to any server.\n4. Panchang calculations are based on standard astronomical methods and may be approximate.',
      'contactFeedback': 'Contact / Feedback',
      'contactFeedbackBody':
          'Your feedback matters!\n\nEmail us at: support@vinayakamsolutions.com\n\nShare suggestions, issues, or questions about the app.',
      'gallery': 'Bhakti Gallery',
      'gallerySubtitle': 'Darshan collections',
      'artworkSoon': 'Artwork coming soon',
      'artworkSoonBody':
          'Artwork for this collection is not yet available. The description is shown below.',
      'collection': 'Collection',
      'item': 'Item',
      'detail': 'Details',
      'adFreeNote': 'This screen never shows ads mid-experience.',
      'bannerAds': 'Ads',
      'premium': 'Premium',
      'adSupportNote': 'Ads are never shown during Jap.',
      'notifications': 'Notifications',
      'notificationPermission':
          'Notification permission is required for the daily reminder.',
      'permissionDenied':
          'Notification permission was not granted. You can enable it from system settings.',
      'notifTitle': 'JapMitra',
      'notifBody': 'Time for your daily Jap.',
      'notifBodyMantra': 'Complete your daily Jap.',
      'setDob': 'Set Date of Birth',
      'editDob': 'Edit DOB: ',
      'deleteDob': 'Delete DOB',
      'dobPrefix': 'DOB: ',
      'announcement': 'Special',
      'inspiration': 'Inspiration',
      'quoteDaily': 'A new resolve and new faith every day.',
      'from': 'from',
      'goalSetting': 'Daily Goal',
      'malaShort': 'Mala',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'days': 'days',
      'sanskritWrong': 'Note: Mantra accuracy review is ongoing.',
      'builtIn': 'Built-in',
      'japNow': 'Start Jap',
      'resume': 'Resume',
      'selected': 'Selected',
      'close': 'Close',
      'deities': 'Deities',
      'temples': 'Temples',
      'festivalToday': "Today's festival",
      'rashifalDesc': "View today's Rashifal",
      'astroTitle': 'Consult an Acharya',
      'astroSubtitle': 'Personal guidance over a private call',
      'astroSpecialities': 'Specialities',
      'astroLanguages': 'Speaks',
      'astroAvailability': 'Available',
      'astroBasedIn': 'Based in',
      'astroFee': 'Consultation',
      'astroMinutes': 'min',
      'astroCall': 'Call',
      'astroWhatsapp': 'WhatsApp',
      'astroCallFailed':
          'Could not start the call. Please dial the number manually.',
      'astroWhatsappFailed':
          'Could not open WhatsApp. Please dial the number manually.',
      'astroNoBooking':
          'No payment or booking happens in the app — please call directly.',
      'mantraFontSize': 'Mantra Font Size',
      'mantraFontSizeNote':
          'This changes only how the mantra looks. Your tap count is not affected.',
      'sizeSmall': 'Small',
      'sizeMedium': 'Medium',
      'sizeLarge': 'Large',
      'sizeExtraLarge': 'Extra Large',
      'myRashi': 'My Sign',
      'setAsMySign': 'Set as my sign',
      'clearMySign': 'Clear my sign',
      'rashiNotSetNote': 'Pick a sign and it will be highlighted here.',
      'rashifalUnavailableNote':
          'Today\u2019s rashifal content is not available yet. We only show rashifal from a verified source.',
      'rashifalToday': "Today's Rashifal",
      'rashifalPrevDay': 'Previous day',
      'rashifalNextDay': 'Next day',
      'rashifalTodayShort': 'Today',
      'rashifalPickSign': 'Pick a sign',
      'rashifalFutureNote':
          'Rashifal for a future date is not available. Please choose today or a past date.',
      'rashifalFromCache': 'Offline — saved data',
      'rashifalFromRemote': 'Fresh data',
      'rashifalRetry': 'Retry',
      'rashifalDisclaimer':
          'This horoscope is daily guidance based on traditional astrological beliefs. It is not a scientifically established prediction or a guarantee of outcomes.',
      'calculate': 'Calculate',
      'calculateNumerology': 'Calculate my numbers',
      'forDate': 'For date',
      'traditionalNote':
          'Traditional numerology associations — not a scientific prediction.',
      'astroPhotoLabel': 'Photograph of the astrologer',
      'customMantraName': 'Mantra Name',
      'optional': 'Optional',
      'customMantraText': 'Mantra Text',
      'deityPhoto': 'Deity photo',
      'choosePhoto': 'Choose photo',
      'replacePhoto': 'Replace photo',
      'removePhoto': 'Remove photo',
      'addCustomMantra': 'Add custom mantra',
      'deleteCustomMantra': 'Delete mantra',
      'deleteCustomMantraBody':
          'This mantra and its jap count will be permanently removed.',
      'customMantraAdded': 'Mantra added.',
      'photoFailed':
          'That photo could not be used — the mantra was saved without it.',
      'noFestivalToday': 'No festival or vrat today.',
      'viewFullPanchang': 'View full Panchang',
      'timings': 'Timings',
    }
  };

  String t(String k) => _v[locale.languageCode]?[k] ?? _v['hi']![k] ?? k;
  bool get isHindi => locale.languageCode == 'hi';
}

class _Delegate extends LocalizationsDelegate<AppLocalizations> {
  const _Delegate();
  @override
  bool isSupported(Locale l) => ['hi', 'en'].contains(l.languageCode);
  @override
  Future<AppLocalizations> load(Locale l) async => AppLocalizations(l);
  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) =>
      false;
}
